name: "Run Contract Tests"
description: "Run Contract tests"
inputs:
  environment:
    description: "Environment to run tests against"
    required: true
  checkout_ref:
    description: "Ref to checkout"
    required: true
  cross_browser:
    description: "Run E2E with playwright config with all devices"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Checkout code"
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.checkout_ref }}
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: "Install dependencies"
      shell: bash
      run: |
        npm ci --ignore-scripts
    - name: "Run contract tests ${{inputs.environment}}"
      shell: bash
      run: |
        npm run contract
